# Generated by Django 5.2 on 2025-04-08 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Linac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_performed', models.DateField(auto_now_add=True)),
                ('test_01', models.FloatField(blank=True, null=True)),
                ('test_02', models.FloatField(blank=True, null=True)),
                ('test_03', models.FloatField(blank=True, null=True)),
                ('test_04', models.FloatField(blank=True, null=True)),
                ('test_05', models.FloatField(blank=True, null=True)),
                ('test_06', models.FloatField(blank=True, null=True)),
                ('test_07', models.FloatField(blank=True, null=True)),
                ('test_08', models.FloatField(blank=True, null=True)),
                ('test_09', models.FloatField(blank=True, null=True)),
                ('test_10', models.FloatField(blank=True, null=True)),
                ('test_11', models.FloatField(blank=True, null=True)),
                ('test_12', models.FloatField(blank=True, null=True)),
                ('test_13', models.FloatField(blank=True, null=True)),
                ('test_14', models.FloatField(blank=True, null=True)),
                ('test_15', models.FloatField(blank=True, null=True)),
                ('test_16', models.FloatField(blank=True, null=True)),
                ('test_17', models.FloatField(blank=True, null=True)),
                ('test_18', models.FloatField(blank=True, null=True)),
                ('test_19', models.FloatField(blank=True, null=True)),
                ('test_20', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QAID_Manager.linac')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
