# Generated by Django 5.2 on 2025-04-18 07:57

import QAID_Manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0002_filmupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmupload',
            name='temp_lines',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='filmupload',
            name='image',
            field=models.ImageField(upload_to=QAID_Manager.models.fieldsize_film_upload_path),
        ),
    ]
