# Generated by Django 5.2 on 2025-05-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0003_filmupload_temp_lines_alter_filmupload_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('lines_json', models.TextField()),
            ],
        ),
    ]
