# Generated by Django 5.2 on 2025-05-06 05:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0004_templines'),
    ]

    operations = [
        migrations.AddField(
            model_name='templines',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
