# Generated by Django 5.2 on 2025-05-08 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0005_templines_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollimatorIsocenterCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image_original', models.ImageField(upload_to='film_uploads/')),
                ('image_cropped', models.ImageField(blank=True, null=True, upload_to='film_cropped/')),
                ('image_result', models.ImageField(blank=True, null=True, upload_to='film_results/')),
                ('mech_center_x', models.FloatField()),
                ('mech_center_y', models.FloatField()),
                ('coll_center_x', models.FloatField()),
                ('coll_center_y', models.FloatField()),
                ('offset_x_mm', models.FloatField()),
                ('offset_y_mm', models.FloatField()),
                ('total_offset_mm', models.FloatField()),
                ('wobble_diameter_mm', models.FloatField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
