# Generated by Django 5.2 on 2025-07-14 06:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0006_collimatorisocentercheck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QAStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('passed', 'QA Passed'), ('minor_service', 'Needs Minor Service'), ('major_service', 'Needs Major Service'), ('failed', 'QA Failed')], max_length=50)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'QA Statuses',
            },
        ),
        migrations.CreateModel(
            name='QATest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('test_type', models.CharField(choices=[('mechanical', 'Mechanical Test'), ('beam', 'Beam Test'), ('film', 'Film Analysis'), ('isocenter', 'Isocenter Test')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('tolerance_value', models.FloatField()),
                ('tolerance_unit', models.CharField(max_length=20)),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['test_type', 'order_index'],
            },
        ),
        migrations.AlterModelOptions(
            name='linac',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='qarecord',
            options={'ordering': ['-date_performed']},
        ),
        migrations.AddField(
            model_name='linac',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linac',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='linac',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='qarecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='QASchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_physicist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('linac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QAID_Manager.linac')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QAID_Manager.qastatus')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.AddField(
            model_name='qarecord',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QAID_Manager.qastatus'),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('qa_create', 'QA Record Created'), ('qa_update', 'QA Record Updated'), ('film_upload', 'Film Uploaded'), ('report_generated', 'Report Generated'), ('settings_changed', 'Settings Changed')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
