# Generated by Django 5.2 on 2025-07-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0010_gantryfilmupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='collimatorfilmupload',
            name='extracted_dpi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filmupload',
            name='extracted_dpi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantryfilmupload',
            name='extracted_dpi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
