# Generated by Django 5.2 on 2025-07-23 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0011_collimatorfilmupload_extracted_dpi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAFilmAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('fieldsize', 'Field Size Analysis'), ('collimator_isocenter', 'Collimator Isocenter'), ('gantry_isocenter', 'Gantry Isocenter')], max_length=50)),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='qa_results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qa_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_analyses', to='QAID_Manager.qarecord')),
            ],
            options={
                'verbose_name_plural': 'QA Film Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QATestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.IntegerField()),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qa_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_notes', to='QAID_Manager.qarecord')),
            ],
            options={
                'verbose_name_plural': 'QA Test Notes',
                'ordering': ['test_number'],
                'unique_together': {('qa_record', 'test_number')},
            },
        ),
    ]
