# Generated by Django 5.2 on 2025-07-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0012_qafilmanalysis_qatestnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linac',
            options={'ordering': ['name'], 'verbose_name': 'LINAC', 'verbose_name_plural': 'LINACs'},
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_modelling_info',
            field=models.TextField(blank=True, verbose_name='Beam Modelling Information'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_info',
            field=models.TextField(blank=True, verbose_name='CAT Information'),
        ),
        migrations.AddField(
            model_name='linac',
            name='certification_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày đến hạn Kiểm định'),
        ),
        migrations.AddField(
            model_name='linac',
            name='dosimetry_method',
            field=models.CharField(blank=True, choices=[('SAD_TRS398', 'SAD (TRS398)'), ('SSD_TG51', 'SSD (TG51)')], max_length=20, verbose_name='Phương pháp chuẩn liều'),
        ),
        migrations.AddField(
            model_name='linac',
            name='energy',
            field=models.CharField(blank=True, choices=[('6MV', '6MV'), ('6MV_FFF', '6MV FFF'), ('10MV', '10MV'), ('10MV_FFF', '10MV FFF'), ('6MeV', '6MeV'), ('9MeV', '9MeV'), ('12MeV', '12MeV'), ('15MeV', '15MeV')], max_length=10, verbose_name='Năng lượng'),
        ),
        migrations.AddField(
            model_name='linac',
            name='installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày lắp đặt'),
        ),
        migrations.AddField(
            model_name='linac',
            name='series_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Series Number'),
        ),
        migrations.AlterField(
            model_name='linac',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên máy'),
        ),
    ]
