# Generated by Django 5.2 on 2025-07-23 08:22

from django.db import migrations, models
import json


def convert_energy_to_json(apps, schema_editor):
    """Convert existing energy values to JSON format"""
    Linac = apps.get_model('QAID_Manager', 'Linac')
    for linac in Linac.objects.all():
        if linac.energy and linac.energy != '':
            # Convert single value to list and store as JSON string
            linac.energy = json.dumps([linac.energy])
        else:
            # Empty or null values become empty list
            linac.energy = json.dumps([])
        linac.save()


def convert_energy_from_json(apps, schema_editor):
    """Convert JSON energy values back to single value (for rollback)"""
    Linac = apps.get_model('QAID_Manager', 'Linac')
    for linac in Linac.objects.all():
        try:
            if linac.energy:
                energy_list = json.loads(linac.energy)
                linac.energy = energy_list[0] if energy_list else ''
            else:
                linac.energy = ''
        except (json.JSONDecodeError, IndexError):
            linac.energy = ''
        linac.save()


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0013_alter_linac_options_linac_beam_modelling_info_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_energy_to_json, convert_energy_from_json),
        migrations.AlterField(
            model_name='linac',
            name='energy',
            field=models.CharField(blank=True, max_length=200, verbose_name='Năng lượng'),
        ),
    ]
