# Generated by Django 5.2 on 2025-07-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0014_alter_linac_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linac',
            name='energy',
            field=models.JSONField(blank=True, default=list, verbose_name='Năng lượng'),
        ),
    ]
