# Generated by Django 5.2 on 2025-07-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0016_alter_linac_options_alter_linac_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linac',
            name='cat_collimator_isocenter',
            field=models.FloatField(blank=True, null=True, verbose_name='Collimator Iso (± 1mm)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_d10_10mv',
            field=models.FloatField(blank=True, null=True, verbose_name='D10 - 10 MV (± 1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_d10_6mv',
            field=models.FloatField(blank=True, null=True, verbose_name='D10 - 6 MV (± 1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_field_size_12x12',
            field=models.FloatField(blank=True, null=True, verbose_name='Field-size (12x12cm) (± 1mm)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_10mv_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 10 MV - Crossline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_10mv_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 10 MV - Inline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_12mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 12 MeV - Crossline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_12mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 12 MeV - Inline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_15mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 15 MeV - Crossline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_15mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 15 MeV - Inline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_6mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 6 MeV - Crossline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_6mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 6 MeV - Inline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_6mv_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 6 MV - Crossline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_6mv_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 6 MV - Inline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_9mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 9 MeV - Crossline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_9mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 9 MeV - Inline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_gantry_isocenter',
            field=models.FloatField(blank=True, null=True, verbose_name='Gantry Iso (± 2mm)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_high_contrast',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='High Contrast (Spatial resolution)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_low_contrast',
            field=models.FloatField(blank=True, null=True, verbose_name='Low Contrast (< 3.0%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_10mv',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 10 MV (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_10mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 10 MV FFF (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_12mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 12 MeV (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_15mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 15 MeV (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_6mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 6 MeV (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_6mv',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 6 MV (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_6mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 6 MV FFF (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_9mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 9 MeV (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_pdd_20_10_10mv',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD 20/10 - 10 MV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_pdd_20_10_10mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD 20/10 - 10 MV FFF'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_pdd_20_10_6mv',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD 20/10 - 6 MV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_pdd_20_10_6mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD 20/10 - 6 MV FFF'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_r80_12mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R80 - 12 MeV (± 1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_r80_15mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R80 - 15 MeV (± 1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_r80_6mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R80 - 6 MeV (± 1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_r80_9mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R80 - 9 MeV (± 1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_sagittal_geometric_scale',
            field=models.FloatField(blank=True, null=True, verbose_name='Sagittal Geometric Scale (± 1 mm)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_10mv_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 10 MV - Crossline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_10mv_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 10 MV - Inline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_12mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 12 MeV - Crossline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_12mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 12 MeV - Inline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_15mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 15 MeV - Crossline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_15mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 15 MeV - Inline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_6mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 6 MeV - Crossline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_6mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 6 MeV - Inline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_6mv_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 6 MV - Crossline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_6mv_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 6 MV - Inline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_9mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 9 MeV - Crossline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_9mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 9 MeV - Inline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_table_height',
            field=models.FloatField(blank=True, null=True, verbose_name='Table height'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_table_height_isocenter',
            field=models.FloatField(blank=True, null=True, verbose_name='Table height Iso'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_table_isocenter',
            field=models.FloatField(blank=True, null=True, verbose_name='Table Iso'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_table_lateral',
            field=models.FloatField(blank=True, null=True, verbose_name='Table lateral'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_table_long',
            field=models.FloatField(blank=True, null=True, verbose_name='Table long'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_table_movement_accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='Table Movement Assisting Accuracy (± 1 mm)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_table_rotation',
            field=models.FloatField(blank=True, null=True, verbose_name='Table rotation'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_tmr_10mv',
            field=models.FloatField(blank=True, null=True, verbose_name='TMR - 10 MV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_tmr_10mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='TMR - 10 MV FFF'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_tmr_6mv',
            field=models.FloatField(blank=True, null=True, verbose_name='TMR - 6 MV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_tmr_6mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='TMR - 6 MV FFF'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_transverse_horizontal_scale',
            field=models.FloatField(blank=True, null=True, verbose_name='Transverse Horizontal Scale (± 1 mm)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_transverse_vertical_scale',
            field=models.FloatField(blank=True, null=True, verbose_name='Transverse Vertical Scale (± 1 mm)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_uniformity',
            field=models.FloatField(blank=True, null=True, verbose_name='Uniformity (< 1.5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_wedge_factor_10mv',
            field=models.FloatField(blank=True, null=True, verbose_name='Wedge Factor - 10 MV (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_wedge_factor_6mv',
            field=models.FloatField(blank=True, null=True, verbose_name='Wedge Factor - 6 MV (<1%)'),
        ),
        migrations.DeleteModel(
            name='CATTestResult',
        ),
    ]
