# Generated by Django 5.2 on 2025-07-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0017_linac_cat_collimator_isocenter_linac_cat_d10_10mv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_10mv',
            field=models.FloatField(blank=True, null=True, verbose_name='Độ sâu chuẩn liều - 10 MV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_10mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='Độ sâu chuẩn liều - 10 MV FFF'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_12mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Độ sâu chuẩn liều - 12 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_15mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Độ sâu chuẩn liều - 15 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_6mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Độ sâu chuẩn liều - 6 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_6mv',
            field=models.FloatField(blank=True, null=True, verbose_name='Độ sâu chuẩn liều - 6 MV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_6mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='Độ sâu chuẩn liều - 6 MV FFF'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_9mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Độ sâu chuẩn liều - 9 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_10mv',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 10 MV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_10mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 10 MV FFF'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_12mev',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 12 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_15mev',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 15 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_6mev',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 6 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_6mv',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 6 MV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_6mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 6 MV FFF'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_9mev',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 9 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_10mv',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 10 MV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_10mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 10 MV FFF'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_12mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 12 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_15mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 15 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_6mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 6 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_6mv',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 6 MV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_6mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 6 MV FFF'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_9mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 9 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_10mv',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 10 MV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_10mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 10 MV FFF'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_12mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 12 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_15mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 15 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_6mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 6 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_6mv',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 6 MV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_6mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 6 MV FFF'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_9mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 9 MeV'),
        ),
    ]
