# Generated by Django 5.2 on 2025-07-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0018_linac_beam_dose_ref_depth_10mv_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosimeter',
            options={'ordering': ['name'], 'verbose_name': 'Dosimeter', 'verbose_name_plural': 'Dosimeters'},
        ),
        migrations.AlterModelOptions(
            name='linac',
            options={'ordering': ['name'], 'verbose_name': 'LINAC', 'verbose_name_plural': 'LINACs'},
        ),
        migrations.AlterModelOptions(
            name='qarecord',
            options={'ordering': ['-date_performed'], 'verbose_name': 'QA Record', 'verbose_name_plural': 'QA Records'},
        ),
        migrations.AlterModelOptions(
            name='qaschedule',
            options={'ordering': ['scheduled_date'], 'verbose_name': 'QA Schedule', 'verbose_name_plural': 'QA Schedules'},
        ),
        migrations.AlterModelOptions(
            name='qatest',
            options={'ordering': ['test_type', 'order_index'], 'verbose_name': 'QA Test', 'verbose_name_plural': 'QA Tests'},
        ),
        migrations.AddField(
            model_name='dosimeter',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hãng sản xuất'),
        ),
        migrations.AddField(
            model_name='dosimeter',
            name='calibration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày chuẩn'),
        ),
        migrations.AddField(
            model_name='dosimeter',
            name='calibration_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='Hệ số chuẩn (N_d,w)'),
        ),
        migrations.AddField(
            model_name='dosimeter',
            name='calibration_lab',
            field=models.CharField(blank=True, max_length=200, verbose_name='Phòng thí nghiệm chuẩn'),
        ),
        migrations.AddField(
            model_name='dosimeter',
            name='calibration_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Áp suất chuẩn (P₀)'),
        ),
        migrations.AddField(
            model_name='dosimeter',
            name='calibration_radiation_source',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nguồn bức xạ chuẩn'),
        ),
        migrations.AddField(
            model_name='dosimeter',
            name='calibration_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Nhiệt độ chuẩn (T₀)'),
        ),
        migrations.AddField(
            model_name='dosimeter',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Số chứng chỉ'),
        ),
        migrations.AddField(
            model_name='dosimeter',
            name='series_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Số series'),
        ),
        migrations.AlterField(
            model_name='dosimeter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='dosimeter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên buồng ion'),
        ),
    ]
