# Generated by Django 5.2 on 2025-07-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0019_alter_dosimeter_options_alter_linac_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicsParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Parameter Name')),
                ('parameter_type', models.CharField(choices=[('ks_coefficients', 'Ks Coefficients (TRS398)'), ('kqqo', 'k_QQo (Beam Quality Correction)'), ('ndw', 'N_d,w (Dosimeter Calibration Factor)'), ('kpol', 'Kpol (Polarity Correction)'), ('ktp', 'Ktp (Temperature & Pressure)'), ('other', 'Other Physics Parameter')], max_length=50, verbose_name='Parameter Type')),
                ('energy', models.CharField(blank=True, max_length=20, verbose_name='Energy (MV/MeV)')),
                ('beam_type', models.CharField(choices=[('photon', 'Photon'), ('electron', 'Electron'), ('both', 'Both')], default='photon', max_length=20, verbose_name='Beam Type')),
                ('parameter_values', models.JSONField(default=dict, verbose_name='Parameter Values')),
                ('voltage_ratio', models.FloatField(blank=True, null=True, verbose_name='Voltage Ratio (V1/V2)')),
                ('a0_coefficient', models.FloatField(blank=True, null=True, verbose_name='a0 Coefficient')),
                ('a1_coefficient', models.FloatField(blank=True, null=True, verbose_name='a1 Coefficient')),
                ('a2_coefficient', models.FloatField(blank=True, null=True, verbose_name='a2 Coefficient')),
                ('reference_energy', models.CharField(blank=True, max_length=20, verbose_name='Reference Energy')),
                ('kqqo_value', models.FloatField(blank=True, null=True, verbose_name='k_QQo Value')),
                ('chamber_type', models.CharField(blank=True, max_length=100, verbose_name='Chamber Type')),
                ('chamber_volume', models.FloatField(blank=True, null=True, verbose_name='Chamber Volume (cm³)')),
                ('reference_standard', models.CharField(blank=True, max_length=100, verbose_name='Reference Standard')),
                ('reference_table', models.CharField(blank=True, max_length=100, verbose_name='Reference Table')),
                ('reference_page', models.CharField(blank=True, max_length=20, verbose_name='Reference Page')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Physics Parameter',
                'verbose_name_plural': 'Physics Parameters',
                'ordering': ['parameter_type', 'energy', 'name'],
            },
        ),
    ]
