# Generated by Django 5.2 on 2025-07-30 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0020_physicsparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoseCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.CharField(max_length=20)),
                ('phantom', models.CharField(choices=[('solid', 'Solid Phantom'), ('water', 'Water Phantom')], max_length=20)),
                ('raw_measurement', models.FloatField(verbose_name='Raw Measurement (nC)')),
                ('ktp_result', models.FloatField(verbose_name='Ktp Result')),
                ('kpol_result', models.FloatField(verbose_name='Kpol Result')),
                ('ks_result', models.FloatField(verbose_name='Ks Result')),
                ('solid_phantom_factor', models.FloatField(blank=True, null=True, verbose_name='Solid Phantom Factor')),
                ('mq_result', models.FloatField(verbose_name='MQ Result (nC)')),
                ('dwq_zref', models.FloatField(verbose_name='Dw,Q(zref) (cGy)')),
                ('dwq_zmax', models.FloatField(verbose_name='Dw,Q(zmax) (cGy)')),
                ('pdd_20_10', models.FloatField(blank=True, null=True, verbose_name='PDD(20/10)')),
                ('tmr', models.FloatField(blank=True, null=True, verbose_name='TMR')),
                ('tpr_20_10', models.FloatField(blank=True, null=True, verbose_name='TPR(20/10)')),
                ('kq_factor', models.FloatField(blank=True, null=True, verbose_name='Kq Factor')),
                ('m_ref', models.FloatField(blank=True, null=True, verbose_name='Mref (FS10x10)')),
                ('m_left', models.FloatField(blank=True, null=True, verbose_name='MLeft (FS20x20)')),
                ('m_right', models.FloatField(blank=True, null=True, verbose_name='MRight (FS20x20)')),
                ('m_gun', models.FloatField(blank=True, null=True, verbose_name='MGun (FS20x20)')),
                ('m_tar', models.FloatField(blank=True, null=True, verbose_name='MTar (FS20x20)')),
                ('m_mid', models.FloatField(blank=True, null=True, verbose_name='Mmid (FS20x20)')),
                ('m_wedge', models.FloatField(blank=True, null=True, verbose_name='Mwedge (FS10x10)')),
                ('m_dmax', models.FloatField(blank=True, null=True, verbose_name='Mdmax (FS10x10)')),
                ('symmetry_crossline', models.FloatField(blank=True, null=True, verbose_name='Symmetry Crossline (%)')),
                ('symmetry_inline', models.FloatField(blank=True, null=True, verbose_name='Symmetry Inline (%)')),
                ('flatness_crossline', models.FloatField(blank=True, null=True, verbose_name='Flatness Crossline (%)')),
                ('flatness_inline', models.FloatField(blank=True, null=True, verbose_name='Flatness Inline (%)')),
                ('output_factor', models.FloatField(blank=True, null=True, verbose_name='Output Factor')),
                ('wedge_factor', models.FloatField(blank=True, null=True, verbose_name='Wedge Factor')),
                ('beam_energy_d10', models.FloatField(blank=True, null=True, verbose_name='Beam Energy (D10)')),
                ('absolute_dose_deviation', models.FloatField(blank=True, null=True, verbose_name='Lieu tuyet doi')),
                ('energy_stability_d10', models.FloatField(blank=True, null=True, verbose_name='Su on dinh cua nang luong (D10)')),
                ('symmetry_vs_commissioning', models.FloatField(blank=True, null=True, verbose_name='Tinh doi xung so voi gia tri tai thoi diem commissioning')),
                ('flatness_vs_commissioning', models.FloatField(blank=True, null=True, verbose_name='Tinh phang so voi gia tri tai thoi diem commissioning')),
                ('output_factor_deviation', models.FloatField(blank=True, null=True, verbose_name='He so lieu loi ra theo kich thuoc truong chieu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QAID_Manager.dosimeter')),
                ('linac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QAID_Manager.linac')),
                ('qa_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_calculations', to='QAID_Manager.qarecord')),
            ],
            options={
                'verbose_name': 'Dose Calculation',
                'verbose_name_plural': 'Dose Calculations',
                'ordering': ['-created_at'],
            },
        ),
    ]
