# Generated by Django 5.2 on 2025-07-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0021_dosecalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosecalculation',
            name='a0',
            field=models.FloatField(blank=True, null=True, verbose_name='a0 Coefficient'),
        ),
        migrations.AddField(
            model_name='dosecalculation',
            name='a1',
            field=models.FloatField(blank=True, null=True, verbose_name='a1 Coefficient'),
        ),
        migrations.AddField(
            model_name='dosecalculation',
            name='a2',
            field=models.FloatField(blank=True, null=True, verbose_name='a2 Coefficient'),
        ),
        migrations.AddField(
            model_name='dosecalculation',
            name='m1',
            field=models.FloatField(blank=True, null=True, verbose_name='M1'),
        ),
        migrations.AddField(
            model_name='dosecalculation',
            name='m2',
            field=models.FloatField(blank=True, null=True, verbose_name='M2'),
        ),
        migrations.AddField(
            model_name='dosecalculation',
            name='m_minus',
            field=models.FloatField(blank=True, null=True, verbose_name='M-'),
        ),
        migrations.AddField(
            model_name='dosecalculation',
            name='m_plus',
            field=models.FloatField(blank=True, null=True, verbose_name='M+'),
        ),
        migrations.AddField(
            model_name='dosecalculation',
            name='pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Pressure (hPa)'),
        ),
        migrations.AddField(
            model_name='dosecalculation',
            name='temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperature (°C)'),
        ),
        migrations.AddField(
            model_name='dosecalculation',
            name='v1',
            field=models.FloatField(blank=True, null=True, verbose_name='V1'),
        ),
        migrations.AddField(
            model_name='dosecalculation',
            name='v1_v2_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='V1/V2 Ratio'),
        ),
        migrations.AddField(
            model_name='dosecalculation',
            name='v2',
            field=models.FloatField(blank=True, null=True, verbose_name='V2'),
        ),
    ]
