# Generated by Django 5.2 on 2025-07-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0022_dosecalculation_a0_dosecalculation_a1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosecalculation',
            name='m_d10',
            field=models.FloatField(blank=True, null=True, verbose_name='Md10 (FS10x10, SSD100)'),
        ),
        migrations.AlterField(
            model_name='dosecalculation',
            name='m_dmax',
            field=models.FloatField(blank=True, null=True, verbose_name='Mdmax (FS10x10, SSD100)'),
        ),
    ]
