# Generated by Django 5.2 on 2025-08-04 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0023_dosecalculation_m_d10_alter_dosecalculation_m_dmax'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qaschedule',
            name='assigned_physicist',
        ),
        migrations.AddField(
            model_name='qaschedule',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='Manual Schedule'),
        ),
        migrations.AddField(
            model_name='qaschedule',
            name='performer1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_schedules_performer1', to=settings.AUTH_USER_MODEL, verbose_name='QA Performer 1'),
        ),
        migrations.AddField(
            model_name='qaschedule',
            name='performer2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_schedules_performer2', to=settings.AUTH_USER_MODEL, verbose_name='QA Performer 2'),
        ),
        migrations.AddField(
            model_name='qaschedule',
            name='qa_reason',
            field=models.TextField(blank=True, verbose_name='QA Reason'),
        ),
        migrations.CreateModel(
            name='VietnameseHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Holiday Name')),
                ('date', models.DateField(verbose_name='Holiday Date')),
                ('holiday_type', models.CharField(choices=[('national', 'National Holiday'), ('regional', 'Regional Holiday'), ('observance', 'Observance')], default='national', max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vietnamese Holiday',
                'verbose_name_plural': 'Vietnamese Holidays',
                'ordering': ['date'],
                'unique_together': {('date', 'name')},
            },
        ),
    ]
