# Generated by Django 5.2 on 2025-08-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0024_remove_qaschedule_assigned_physicist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qaschedule',
            options={'ordering': ['month_year', 'linac__name'], 'verbose_name': 'QA Schedule', 'verbose_name_plural': 'QA Schedules'},
        ),
        migrations.RemoveField(
            model_name='qaschedule',
            name='is_manual',
        ),
        migrations.RemoveField(
            model_name='qaschedule',
            name='scheduled_date',
        ),
        migrations.AddField(
            model_name='qaschedule',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='QA Results Accepted'),
        ),
        migrations.AddField(
            model_name='qaschedule',
            name='month_year',
            field=models.DateField(blank=True, help_text='First day of the month for this QA schedule', null=True),
        ),
        migrations.AddField(
            model_name='qaschedule',
            name='qa_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date QA was performed'),
        ),
    ]
