# Generated by Django 5.2 on 2025-08-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0025_alter_qaschedule_options_remove_qaschedule_is_manual_and_more'),
    ]

    operations = [
    ]
