# Generated by Django 5.2 on 2025-08-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0026_update_existing_qaschedules'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qaschedule',
            unique_together={('linac', 'month_year')},
        ),
    ]
