# Generated by Django 5.2 on 2025-08-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0027_alter_qaschedule_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaschedule',
            name='expected_qa_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expected QA Date'),
        ),
        migrations.AlterField(
            model_name='qaschedule',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Failed QA Accepted'),
        ),
        migrations.AlterField(
            model_name='qaschedule',
            name='month_year',
            field=models.DateField(blank=True, null=True, verbose_name='Month/Year'),
        ),
        migrations.AlterField(
            model_name='qaschedule',
            name='qa_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual QA Date'),
        ),
    ]
