# Generated by Django 5.2 on 2025-08-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0028_qaschedule_expected_qa_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaschedule',
            name='failed_tests_data',
            field=models.JSONField(blank=True, default=list, verbose_name='Failed Tests Data'),
        ),
    ]
