# Generated by Django 5.2.8 on 2025-11-08 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0029_qaschedule_failed_tests_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qarecord',
            name='qa_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_records', to='QAID_Manager.qaschedule', verbose_name='QA Schedule'),
        ),
        migrations.AddField(
            model_name='qaschedule',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Accepted At'),
        ),
        migrations.AddField(
            model_name='qaschedule',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_qa_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Accepted By'),
        ),
        migrations.AddField(
            model_name='qaschedule',
            name='is_adhoc',
            field=models.BooleanField(default=False, verbose_name='Ad-hoc QA Session'),
        ),
        migrations.AddField(
            model_name='qaschedule',
            name='notes_edit_history',
            field=models.JSONField(blank=True, default=list, verbose_name='Notes Edit History'),
        ),
        migrations.AlterField(
            model_name='qastatus',
            name='name',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('passed', 'QA Passed'), ('passed_with_exception', 'Passed with Deviation'), ('minor_service', 'Needs Minor Service'), ('major_service', 'Needs Major Service'), ('failed', 'QA Failed')], max_length=50),
        ),
    ]
