# Generated by Django 5.2.8 on 2025-11-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0030_qarecord_qa_schedule_qaschedule_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_10mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 10 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_11mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 11 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_13mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 13 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_14mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 14 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_15mv',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 15 MV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_15mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 15 MV FFF'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_16mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 16 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_17mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 17 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_18mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 18 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_4mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 4 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_5mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 5 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_7mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 7 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_dose_ref_depth_8mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 8 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_10mev',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 10 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_11mev',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 11 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_13mev',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 13 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_14mev',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 14 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_15mv',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 15 MV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_15mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 15 MV FFF'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_16mev',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 16 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_17mev',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 17 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_18mev',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 18 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_4mev',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 4 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_5mev',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 5 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_7mev',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 7 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_pdd_20_10_8mev',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD20/10 - 8 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_10mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 10 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_11mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 11 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_13mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 13 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_14mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 14 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_15mv',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 15 MV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_15mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 15 MV FFF'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_16mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 16 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_17mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 17 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_18mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 18 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_4mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 4 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_5mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 5 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_7mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 7 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_calculated_8mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR (calculated) - 8 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_10mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 10 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_11mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 11 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_13mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 13 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_14mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 14 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_15mv',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 15 MV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_15mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 15 MV FFF'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_16mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 16 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_17mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 17 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_18mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 18 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_4mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 4 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_5mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 5 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_7mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 7 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_tpr_zreff_8mev',
            field=models.FloatField(blank=True, null=True, verbose_name='TPR or TMR (Zreff) - 8 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_d10_15mv',
            field=models.FloatField(blank=True, null=True, verbose_name='D10 - 15 MV (± 1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_10mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 10 MeV - Crossline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_10mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 10 MeV - Inline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_11mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 11 MeV - Crossline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_11mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 11 MeV - Inline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_13mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 13 MeV - Crossline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_13mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 13 MeV - Inline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_14mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 14 MeV - Crossline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_14mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 14 MeV - Inline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_15mv_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 15 MV - Crossline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_15mv_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 15 MV - Inline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_16mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 16 MeV - Crossline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_16mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 16 MeV - Inline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_17mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 17 MeV - Crossline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_17mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 17 MeV - Inline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_18mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 18 MeV - Crossline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_18mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 18 MeV - Inline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_4mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 4 MeV - Crossline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_4mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 4 MeV - Inline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_5mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 5 MeV - Crossline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_5mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 5 MeV - Inline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_7mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 7 MeV - Crossline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_7mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 7 MeV - Inline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_8mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 8 MeV - Crossline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_flatness_8mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Flatness - 8 MeV - Inline (≤ 5%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_10mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 10 MeV (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_11mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 11 MeV (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_13mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 13 MeV (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_14mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 14 MeV (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_15mv',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 15 MV (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_15mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 15 MV FFF (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_16mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 16 MeV (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_17mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 17 MeV (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_18mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 18 MeV (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_4mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 4 MeV (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_5mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 5 MeV (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_7mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 7 MeV (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_output_factor_8mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Factor - 8 MeV (<1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_pdd_20_10_15mv',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD 20/10 - 15 MV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_pdd_20_10_15mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='PDD 20/10 - 15 MV FFF'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_r80_10mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R80 - 10 MeV (± 1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_r80_11mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R80 - 11 MeV (± 1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_r80_13mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R80 - 13 MeV (± 1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_r80_14mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R80 - 14 MeV (± 1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_r80_16mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R80 - 16 MeV (± 1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_r80_17mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R80 - 17 MeV (± 1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_r80_18mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R80 - 18 MeV (± 1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_r80_4mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R80 - 4 MeV (± 1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_r80_5mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R80 - 5 MeV (± 1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_r80_7mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R80 - 7 MeV (± 1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_r80_8mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R80 - 8 MeV (± 1%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_10mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 10 MeV - Crossline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_10mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 10 MeV - Inline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_11mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 11 MeV - Crossline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_11mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 11 MeV - Inline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_13mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 13 MeV - Crossline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_13mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 13 MeV - Inline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_14mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 14 MeV - Crossline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_14mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 14 MeV - Inline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_15mv_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 15 MV - Crossline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_15mv_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 15 MV - Inline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_16mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 16 MeV - Crossline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_16mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 16 MeV - Inline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_17mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 17 MeV - Crossline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_17mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 17 MeV - Inline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_18mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 18 MeV - Crossline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_18mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 18 MeV - Inline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_4mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 4 MeV - Crossline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_4mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 4 MeV - Inline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_5mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 5 MeV - Crossline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_5mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 5 MeV - Inline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_7mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 7 MeV - Crossline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_7mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 7 MeV - Inline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_8mev_crossline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 8 MeV - Crossline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_symmetry_8mev_inline',
            field=models.FloatField(blank=True, null=True, verbose_name='Symmetry - 8 MeV - Inline (≤ 3%)'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_tmr_15mv',
            field=models.FloatField(blank=True, null=True, verbose_name='TMR - 15 MV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_tmr_15mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='TMR - 15 MV FFF'),
        ),
        migrations.AddField(
            model_name='linac',
            name='cat_wedge_factor_15mv',
            field=models.FloatField(blank=True, null=True, verbose_name='Wedge Factor - 15 MV (<1%)'),
        ),
        migrations.AlterField(
            model_name='linac',
            name='beam_dose_ref_depth_10mv',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 10 MV'),
        ),
        migrations.AlterField(
            model_name='linac',
            name='beam_dose_ref_depth_10mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 10 MV FFF'),
        ),
        migrations.AlterField(
            model_name='linac',
            name='beam_dose_ref_depth_12mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 12 MeV'),
        ),
        migrations.AlterField(
            model_name='linac',
            name='beam_dose_ref_depth_15mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 15 MeV'),
        ),
        migrations.AlterField(
            model_name='linac',
            name='beam_dose_ref_depth_6mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 6 MeV'),
        ),
        migrations.AlterField(
            model_name='linac',
            name='beam_dose_ref_depth_6mv',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 6 MV'),
        ),
        migrations.AlterField(
            model_name='linac',
            name='beam_dose_ref_depth_6mv_fff',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 6 MV FFF'),
        ),
        migrations.AlterField(
            model_name='linac',
            name='beam_dose_ref_depth_9mev',
            field=models.FloatField(blank=True, null=True, verbose_name='Dose Reference Depth - 9 MeV'),
        ),
    ]
