# Generated by Django 5.2.8 on 2025-11-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0031_linac_beam_dose_ref_depth_10mev_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linac',
            name='beam_pdd_20_10_10mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_pdd_20_10_11mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_pdd_20_10_12mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_pdd_20_10_13mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_pdd_20_10_14mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_pdd_20_10_15mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_pdd_20_10_16mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_pdd_20_10_17mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_pdd_20_10_18mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_pdd_20_10_4mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_pdd_20_10_5mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_pdd_20_10_6mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_pdd_20_10_7mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_pdd_20_10_8mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_pdd_20_10_9mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_calculated_10mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_calculated_11mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_calculated_12mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_calculated_13mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_calculated_14mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_calculated_15mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_calculated_16mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_calculated_17mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_calculated_18mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_calculated_4mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_calculated_5mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_calculated_6mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_calculated_7mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_calculated_8mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_calculated_9mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_zreff_10mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_zreff_11mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_zreff_12mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_zreff_13mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_zreff_14mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_zreff_15mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_zreff_16mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_zreff_17mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_zreff_18mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_zreff_4mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_zreff_5mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_zreff_6mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_zreff_7mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_zreff_8mev',
        ),
        migrations.RemoveField(
            model_name='linac',
            name='beam_tpr_zreff_9mev',
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_r50_10mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R50 - 10 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_r50_11mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R50 - 11 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_r50_12mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R50 - 12 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_r50_13mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R50 - 13 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_r50_14mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R50 - 14 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_r50_15mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R50 - 15 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_r50_16mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R50 - 16 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_r50_17mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R50 - 17 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_r50_18mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R50 - 18 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_r50_4mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R50 - 4 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_r50_5mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R50 - 5 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_r50_6mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R50 - 6 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_r50_7mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R50 - 7 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_r50_8mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R50 - 8 MeV'),
        ),
        migrations.AddField(
            model_name='linac',
            name='beam_r50_9mev',
            field=models.FloatField(blank=True, null=True, verbose_name='R50 - 9 MeV'),
        ),
    ]
