# Generated by Django 5.2.8 on 2025-11-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0032_remove_linac_beam_pdd_20_10_10mev_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarecord',
            name='isocenter_matrix_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Isocenter Matrix Data'),
        ),
    ]
