# Generated by Django 5.2.8 on 2025-11-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0033_qarecord_isocenter_matrix_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarecord',
            name='tested_energies',
            field=models.JSONField(blank=True, default=list, verbose_name='Tested Energies'),
        ),
    ]
