# Generated by Django 5.2.8 on 2025-11-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0035_add_beam_test_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization/', verbose_name='Logo')),
                ('organization_name', models.TextField(default='Demo Radiotherapy Physics Department', help_text='Organization display name (multi-line allowed)', verbose_name='Organization Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization Settings',
                'verbose_name_plural': 'Organization Settings',
            },
        ),
    ]
