# Generated by Django 5.2.8 on 2025-11-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0036_organizationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='job_image',
            field=models.ImageField(blank=True, help_text='Image displayed on the right side of the homepage', null=True, upload_to='organization/', verbose_name='Job Image'),
        ),
    ]
