# Generated by Django 5.2.8 on 2025-11-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0037_organizationsettings_job_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationsettings',
            old_name='job_image',
            new_name='right_side_image',
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='right_side_image',
            field=models.ImageField(blank=True, help_text='Image displayed on the right side of the homepage', null=True, upload_to='organization/', verbose_name='Right Side Image'),
        ),
    ]
