# Generated by Django 5.2.8 on 2025-11-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0038_rename_job_image_to_right_side_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationsettings',
            old_name='right_side_image',
            new_name='left_side_image',
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='left_side_image',
            field=models.ImageField(blank=True, help_text='Image displayed on the left side of the homepage', null=True, upload_to='organization/', verbose_name='Left Side Image'),
        ),
    ]
