# Generated by Django 5.2.8 on 2025-11-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0039_rename_right_side_image_to_left_side_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='bottom_image',
            field=models.ImageField(blank=True, help_text='Image displayed at the bottom of the homepage', null=True, upload_to='organization/', verbose_name='Bottom Image'),
        ),
    ]
