# Generated by Django 5.2.8 on 2025-11-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0041_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='report_template',
            field=models.FileField(blank=True, help_text='Upload a DOCX template file for QA reports. Use placeholders like {{LINAC_NAME}}, {{DATE_PERFORMED}}, etc.', null=True, upload_to='organization/reports/', verbose_name='Report Template'),
        ),
    ]
