# Generated by Django 5.2.8 on 2025-11-16 10:39

import QAID_Manager.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0042_add_report_template_to_organizationsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DosimeterDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=QAID_Manager.models.dosimeter_file_upload_path, verbose_name='Document File')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word Document'), ('docx', 'Word Document (DOCX)'), ('png', 'PNG Image'), ('jpg', 'JPEG Image'), ('jpeg', 'JPEG Image'), ('tiff', 'TIFF Image'), ('tif', 'TIFF Image'), ('other', 'Other')], default='other', max_length=50, verbose_name='File Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dosimeter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='QAID_Manager.dosimeter')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dosimeter Document',
                'verbose_name_plural': 'Dosimeter Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LinacDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=QAID_Manager.models.linac_file_upload_path, verbose_name='Document File')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word Document'), ('docx', 'Word Document (DOCX)'), ('png', 'PNG Image'), ('jpg', 'JPEG Image'), ('jpeg', 'JPEG Image'), ('tiff', 'TIFF Image'), ('tif', 'TIFF Image'), ('other', 'Other')], default='other', max_length=50, verbose_name='File Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('linac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='QAID_Manager.linac')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LINAC Document',
                'verbose_name_plural': 'LINAC Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
