# Generated by Django 5.2.8 on 2025-12-14 12:48

import QAID_Manager.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0043_dosimeterdocument_linacdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('dosimeters', 'Dosimeters'), ('machine_qa', 'Machine QA Equipment'), ('psqa', 'PSQA Equipment'), ('tps_his', 'TPS and HIS Equipment'), ('others', 'Others')], max_length=50, verbose_name='Category')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Brand')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('series_number', models.CharField(blank=True, max_length=100, verbose_name='Series Number')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='Certificate Number')),
                ('storage_location', models.CharField(blank=True, max_length=200, verbose_name='Storage Location')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices and Equipment',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=QAID_Manager.models.device_file_upload_path, verbose_name='Document File')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word Document'), ('docx', 'Word Document (DOCX)'), ('png', 'PNG Image'), ('jpg', 'JPEG Image'), ('jpeg', 'JPEG Image'), ('tiff', 'TIFF Image'), ('tif', 'TIFF Image'), ('other', 'Other')], default='other', max_length=50, verbose_name='File Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='QAID_Manager.device')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Document',
                'verbose_name_plural': 'Device Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='collimatorisocentercheck',
            name='user',
        ),
        migrations.DeleteModel(
            name='TempLines',
        ),
        migrations.DeleteModel(
            name='CollimatorIsocenterCheck',
        ),
    ]
