# Generated by Django 5.2.8 on 2025-12-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0044_device_devicedocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(choices=[('dosimeters', 'Dosimeters'), ('machine_qa', 'Machine QA Equipment'), ('psqa', 'PSQA Equipment'), ('tps_his', 'TPS and HIS Equipment'), ('ct_sim', 'CT-Sim'), ('positioning', 'Positioning Equipment'), ('others', 'Others')], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='device',
            name='storage_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location'),
        ),
    ]
