# Generated by Django 5.2.8 on 2025-12-14 13:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0045_alter_device_category_alter_device_storage_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinacServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('pm_service', models.BooleanField(default=False, verbose_name='PM Service')),
                ('equipment_breakdown', models.BooleanField(default=False, verbose_name='Equipment Breakdown')),
                ('issue_description', models.TextField(blank=True, verbose_name='Issue Description')),
                ('follow_up_actions', models.TextField(blank=True, verbose_name='Follow-up Actions')),
                ('downtime', models.CharField(blank=True, max_length=200, verbose_name='Downtime')),
                ('parts_replacement', models.TextField(blank=True, verbose_name='Parts Replacement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('temporary', 'Temporary')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_reports', to=settings.AUTH_USER_MODEL)),
                ('linac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reports', to='QAID_Manager.linac', verbose_name='LINAC')),
            ],
            options={
                'verbose_name': 'LINAC Service Report',
                'verbose_name_plural': 'LINAC Service Reports',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
