# Generated by Django 5.2.8 on 2025-12-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0046_linacservicereport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qaschedule',
            unique_together=set(),
        ),
    ]
