# Generated by Django 5.2.8 on 2026-03-15 12:07

import re
import django.db.models.deletion
from django.db import migrations, models


def migrate_downtime_to_hours(apps, schema_editor):
    LinacServiceReport = apps.get_model('QAID_Manager', 'LinacServiceReport')
    for report in LinacServiceReport.objects.all():
        raw = (report.downtime or '').strip()
        if not raw:
            continue
        # Accept values like: 3, 3h, 3.5h, 2 hours
        match = re.search(r'(\d+(?:\.\d+)?)', raw)
        if match:
            report.downtime_hours = float(match.group(1))
            report.save(update_fields=['downtime_hours'])


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0047_remove_qaschedule_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='linacservicereport',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reports', to='QAID_Manager.device', verbose_name='Device'),
        ),
        migrations.AddField(
            model_name='linacservicereport',
            name='downtime_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='Downtime (hours)'),
        ),
        migrations.RunPython(migrate_downtime_to_hours, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='linacservicereport',
            name='downtime',
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='service_report_template',
            field=models.FileField(blank=True, help_text='Upload a DOCX template file for service reports. Use placeholders like {{REPORT_PRINTING_DATE}}, {{REPORT_PRINTING_MONTH}}, {{REPORT_PRINTING_YEAR}}, and {{SERVICE_TABLE}}.', null=True, upload_to='organization/reports/', verbose_name='Service Report Template'),
        ),
        migrations.AlterField(
            model_name='linacservicereport',
            name='linac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reports', to='QAID_Manager.linac', verbose_name='LINAC'),
        ),
    ]
