# Generated by Django 5.2.8 on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0048_remove_linacservicereport_downtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarecord',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Draft QA Record'),
        ),
    ]

