# Generated by Django 5.2.8 on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0049_qarecord_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarecord',
            name='draft_dose_calculation_state',
            field=models.JSONField(blank=True, default=dict, verbose_name='Draft Dose Calculator State'),
        ),
    ]

