# Generated by Django 5.2.8 on 2026-07-04 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAID_Manager', '0056_dosecalculation_ssd_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Test Type',
                'verbose_name_plural': 'Custom Test Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='qarecord',
            name='custom_test_results',
            field=models.JSONField(blank=True, default=dict, verbose_name='Custom Test Results'),
        ),
        migrations.AlterField(
            model_name='physicsparameters',
            name='parameter_type',
            field=models.CharField(choices=[('ks_coefficients', 'Ks Coefficients (TRS398)'), ('kqqo', 'k_QQo (Beam Quality Correction)'), ('ndw', 'N_d,w (Dosimeter Calibration Factor)'), ('kpol', 'Kpol (Polarity Correction)'), ('ktp', 'Ktp (Temperature & Pressure)'), ('film_analysis', 'Film Analysis Parameters'), ('other', 'Other Physics Parameter')], max_length=50, verbose_name='Parameter Type'),
        ),
        migrations.CreateModel(
            name='CustomTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tolerance_value', models.FloatField()),
                ('tolerance_unit', models.CharField(max_length=20)),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='QAID_Manager.customtesttype')),
            ],
            options={
                'verbose_name': 'Custom Test',
                'verbose_name_plural': 'Custom Tests',
                'ordering': ['order_index'],
            },
        ),
    ]
